Repository DailyMemeProject/DailyMeme, pull requests merged in 2025-07, with the labels that each got.

#9 ✅ add : 회원가입 기능 개발
  build.gradle.kts
  commits.txt
  gradlew
  src/main/java/com/dailymeme/dailymeme/domain/user/controller/UserController.java
  src/main/java/com/dailymeme/dailymeme/domain/user/dto/login/UserLoginRequestDto.java
  src/main/java/com/dailymeme/dailymeme/domain/user/dto/login/UserLoginResponseDto.java
  src/main/java/com/dailymeme/dailymeme/domain/user/dto/signup/UserSignupRequestDto.java
  src/main/java/com/dailymeme/dailymeme/domain/user/dto/signup/UserSignupResponseDto.java
  src/main/java/com/dailymeme/dailymeme/domain/user/entity/User.java
  src/main/java/com/dailymeme/dailymeme/domain/user/enums/UserAuth.java
  src/main/java/com/dailymeme/dailymeme/domain/user/enums/UserStatus.java
  src/main/java/com/dailymeme/dailymeme/domain/user/repository/UserRepository.java
  src/main/java/com/dailymeme/dailymeme/domain/user/service/UserService.java
  src/main/java/com/dailymeme/dailymeme/global/entity/BaseEntity.java
  src/main/kotlin/com/dailymeme/dailymeme/DailyMemeApplication.kt
  src/main/resources/application.properties
  src/test/kotlin/com/dailymeme/dailymeme/http-request.http
Labels: ✨ 기능 제안, 🖥 백엔드

#11 🔀깃허브 템플릿 작성
  .commit_template.txt
  .github/PULL_REQUEST_TEMPLATE/✨-기능-추가.md
  .github/PULL_REQUEST_TEMPLATE/🐞-버그-수정.md
  .github/PULL_REQUEST_TEMPLATE/📚-문서-작성.md
  .github/PULL_REQUEST_TEMPLATE/🧹-기능-리팩토링.md
  build.gradle.kts
Labels: 📚 문서, 상태 : 🔍 리뷰 중

#14 :ambulance: docs : PR 기본 템플릿 설정
  .github/pull_request_template.md
Labels: 📚 문서, 🙋 도움 필요

#17 🔀 PR 템플릿 가독성 향상 및 일부 수정
  .github/pull_request_template.md
Labels: 📚 문서

#16 🔀 댓글 기능 추가
  src/main/java/com/dailymeme/dailymeme/controller/MemeController.java
  src/main/java/com/dailymeme/dailymeme/domain/comment/controller/CommentController.java
  src/main/java/com/dailymeme/dailymeme/domain/comment/dto/CommentRequestDto.java
  src/main/java/com/dailymeme/dailymeme/domain/comment/dto/CommentResponseDto.java
  src/main/java/com/dailymeme/dailymeme/domain/comment/entity/Comment.java
  src/main/java/com/dailymeme/dailymeme/domain/comment/repository/CommentRepository.java
  src/main/java/com/dailymeme/dailymeme/domain/comment/service/CommentService.java
  src/main/java/com/dailymeme/dailymeme/global/config/CorsConfig.java
  src/main/java/com/dailymeme/dailymeme/global/config/MailConfig.java
  src/main/java/com/dailymeme/dailymeme/global/scheduler/MemeScheduler.java
  src/main/java/com/dailymeme/dailymeme/model/Meme.java
  src/main/java/com/dailymeme/dailymeme/model/dto/MemeResponseDto.java
  src/main/java/com/dailymeme/dailymeme/repository/MemeRepository.java
  src/main/java/com/dailymeme/dailymeme/service/MemeService.java
Labels: ✨ 기능 제안, 상태 : 🕓 확인 대기, 상태 : ✅ 완료, 🖥 백엔드

#21 ✅ Spring Security, JWT 구현 완료(#20)
  build.gradle.kts
  src/main/java/com/dailymeme/dailymeme/domain/user/controller/UserController.java
  src/main/java/com/dailymeme/dailymeme/domain/user/dto/login/UserLoginResponseDto.java
  src/main/java/com/dailymeme/dailymeme/domain/user/entity/User.java
  src/main/java/com/dailymeme/dailymeme/domain/user/enums/UserAuth.java
  src/main/java/com/dailymeme/dailymeme/domain/user/repository/UserRepository.java
  src/main/java/com/dailymeme/dailymeme/domain/user/service/UserService.java
  src/main/java/com/dailymeme/dailymeme/global/auth/DelegatedAccessDeniedHandler.java
  src/main/java/com/dailymeme/dailymeme/global/auth/DelegatedAuthenticationEntryPoint.java
  src/main/java/com/dailymeme/dailymeme/global/auth/UserDetailsImpl.java
  src/main/java/com/dailymeme/dailymeme/global/auth/UserDetailsServiceImpl.java
  src/main/java/com/dailymeme/dailymeme/global/config/SecurityConfig.java
  src/main/java/com/dailymeme/dailymeme/global/config/WebConfig.java
  src/main/java/com/dailymeme/dailymeme/global/entity/RefreshToken.java
  src/main/java/com/dailymeme/dailymeme/global/exception/CustomException.java
  src/main/java/com/dailymeme/dailymeme/global/exception/ExceptionResponseBody.java
  src/main/java/com/dailymeme/dailymeme/global/exception/ExceptionType.java
  src/main/java/com/dailymeme/dailymeme/global/exception/GlobalExceptionHandler.java
  src/main/java/com/dailymeme/dailymeme/global/exception/NotFoundException.java
  src/main/java/com/dailymeme/dailymeme/global/jwtutil/AuthenticationScheme.java
  src/main/java/com/dailymeme/dailymeme/global/jwtutil/JwtUtil.java
  src/main/java/com/dailymeme/dailymeme/global/token/dto/TokenRequestDto.java
  src/main/java/com/dailymeme/dailymeme/global/token/dto/TokenResponseDto.java
  src/main/java/com/dailymeme/dailymeme/global/token/filter/JwtAuthFilter.java
  src/main/java/com/dailymeme/dailymeme/global/token/repository/RefreshTokenRepository.java
  src/main/java/com/dailymeme/dailymeme/global/token/tokenservice/TokenService.java
  src/main/resources/application.properties
Labels: 상태 : 🕓 확인 대기, 상태 : 🔍 리뷰 중, 🖥 백엔드

#27 🔀feat : Swagger 기능 추가 (API 테스트용) #26
  build.gradle.kts
  src/main/java/com/dailymeme/dailymeme/global/config/SwaggerConfig.java
  src/main/java/com/dailymeme/dailymeme/global/config/WebConfig.java
  src/main/java/com/dailymeme/dailymeme/global/token/filter/JwtAuthFilter.java
  src/main/kotlin/com/dailymeme/dailymeme/DailyMemeApplication.kt
Labels: 📚 문서, 🙋 도움 필요, 상태 : 🕓 확인 대기, 🌐 프론트엔드, 🖥 백엔드

#29 🔀 사용자 단건, 다건 조회, 정보 변경 기능 추가 (#28)
  src/main/java/com/dailymeme/dailymeme/domain/user/controller/UserController.java
  src/main/java/com/dailymeme/dailymeme/domain/user/dto/info/UserInfoListResponseDto.java
  src/main/java/com/dailymeme/dailymeme/domain/user/dto/info/UserInfoResponseDto.java
  src/main/java/com/dailymeme/dailymeme/domain/user/dto/info/UserInfoUpdateRequestDto.java
  src/main/java/com/dailymeme/dailymeme/domain/user/dto/info/UserInfoUpdateResponseDto.java
  src/main/java/com/dailymeme/dailymeme/domain/user/dto/login/UserLoginResponseDto.java
  src/main/java/com/dailymeme/dailymeme/domain/user/dto/signup/UserSignupRequestDto.java
  src/main/java/com/dailymeme/dailymeme/domain/user/entity/User.java
  src/main/java/com/dailymeme/dailymeme/domain/user/repository/UserRepository.java
  src/main/java/com/dailymeme/dailymeme/domain/user/service/UserService.java
  src/main/resources/application.properties
Labels: 상태 : 🔍 리뷰 중, 상태 : ✅ 완료, 🖥 백엔드
